"""new-migration

Revision ID: 07fa99be186a
Revises: e0ff4d7f0a5a
Create Date: 2025-09-14 09:45:18.381067

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07fa99be186a"
down_revision: Union[str, Sequence[str], None] = "e0ff4d7f0a5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    # безопасно создать enum, если его ещё нет
    status_enum = postgresql.ENUM(
        "in_progress", "completed", "abandoned", name="status"
    )
    status_enum.create(bind, checkfirst=True)

    op.create_table(
        "ent_option",
        sa.Column("guid", sa.UUID(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("option_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
        sa.UniqueConstraint("option_number"),
    )

    op.create_table(
        "ent_attempt",
        sa.Column("guid", sa.UUID(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ent_option_id", sa.Integer(), nullable=True),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "in_progress",
                "completed",
                "abandoned",
                name="status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column(
            "started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deadline_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ent_option_id"], ["ent_option.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )

    op.create_table(
        "ent_attempt_answer",
        sa.Column("guid", sa.UUID(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ent_attempt_id", sa.Integer(), nullable=True),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ent_attempt_id"],
            ["ent_attempt.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )

    op.add_column("questions", sa.Column("subject_id", sa.Integer(), nullable=True))
    op.add_column("questions", sa.Column("ent_option_id", sa.Integer(), nullable=True))

    op.alter_column("questions", "topic_id", existing_type=sa.INTEGER(), nullable=True)

    op.create_foreign_key(None, "questions", "subjects", ["subject_id"], ["id"])
    op.create_foreign_key(None, "questions", "ent_option", ["ent_option_id"], ["id"])

    op.add_column(
        "test_attempt_questions",
        sa.Column(
            "spend_time", sa.Integer(), nullable=True, server_default=sa.text("0")
        ),
    )
    op.add_column(
        "variants",
        sa.Column("weight", sa.Float(), nullable=True, server_default=sa.text("0")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("variants", "weight")
    op.drop_column("test_attempt_questions", "spend_time")
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.alter_column("questions", "topic_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("questions", "ent_option_id")
    op.drop_column("questions", "subject_id")
    op.drop_table("ent_attempt_answer")
    op.drop_table("ent_attempt")
    op.drop_table("ent_option")
    # ### end Alembic commands ###
