"""fix tests models

Revision ID: 1e99634f4af5
Revises: b97d10408736
Create Date: 2025-10-21 11:16:33.168241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e99634f4af5"
down_revision: Union[str, Sequence[str], None] = "b97d10408736"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ent_attempts", "score", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "trainer_attempt_answers",
        "variant_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(
        op.f("trainer_attempt_answers_variant_id_fkey"),
        "trainer_attempt_answers",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "trainer_attempt_answers",
        "variants",
        ["variant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trainer_attempt_answers", type_="foreignkey")
    op.create_foreign_key(
        op.f("trainer_attempt_answers_variant_id_fkey"),
        "trainer_attempt_answers",
        "variants",
        ["variant_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "trainer_attempt_answers",
        "variant_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column("ent_attempts", "score", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
