"""big update after major updates

Revision ID: 2b750c0f99de
Revises: 7701cb79540b
Create Date: 2025-12-09 01:03:18.643760

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b750c0f99de"
down_revision: Union[str, Sequence[str], None] = "7701cb79540b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("original_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("is_recurring", sa.Boolean(), nullable=True),
        sa.Column("trial_days", sa.Integer(), nullable=True),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("limitations", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_type", name="uq_subscription_plan_type"),
    )
    op.create_index(
        "ix_subscription_plans_active",
        "subscription_plans",
        ["is_active", "is_visible"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_plans_is_active"),
        "subscription_plans",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_plans_plan_type"),
        "subscription_plans",
        ["plan_type"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("subscription_plan_id", sa.Integer(), nullable=True),
        sa.Column("plan", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("auto_renew", sa.Boolean(), nullable=True),
        sa.Column("payment_id", sa.Integer(), nullable=True),
        sa.Column("promocode_usage_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["promocode_usage_id"],
            ["promocode_usages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_plan_id"],
            ["subscription_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_subscriptions_expires_at", "subscriptions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_subscriptions_plan", "subscriptions", ["subscription_plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_subscriptions_user_status",
        "subscriptions",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "subscription_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("old_status", sa.String(length=32), nullable=True),
        sa.Column("new_status", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("history_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_subscription_history_created_at",
        "subscription_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_history_subscription_id",
        "subscription_history",
        ["subscription_id"],
        unique=False,
    )
    op.add_column(
        "payments", sa.Column("is_subscription_payment", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "payments", sa.Column("subscription_plan", sa.String(length=32), nullable=True)
    )
    plantype_enum = postgresql.ENUM(
        "NONE", "FREE", "LITE", "PRO", "PREMIUM", name="plantype"
    )
    plantype_enum.create(op.get_bind())
    op.add_column(
        "promocode_usages", sa.Column("activated_plan", plantype_enum, nullable=False)
    )
    op.alter_column(
        "promocode_usages",
        "activated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )

    # Удаляем уникальное ограничение, но сохраняем foreign keys
    op.drop_constraint(
        op.f("uq_promocode_usage_per_student"), "promocode_usages", type_="unique"
    )
    op.add_column(
        "promocodes",
        sa.Column("plan_type", plantype_enum, server_default="LITE", nullable=False),
    )
    op.add_column("promocodes", sa.Column("is_trial", sa.Boolean(), nullable=True))
    op.add_column("promocodes", sa.Column("is_reusable", sa.Boolean(), nullable=True))
    op.alter_column(
        "promocodes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )

    # Меняем индекс на уникальное ограничение
    op.drop_index(op.f("ix_promocodes_code"), table_name="promocodes")
    op.create_unique_constraint("uq_promocodes_code", "promocodes", ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "promocodes", type_="unique")
    op.create_index(op.f("ix_promocodes_code"), "promocodes", ["code"], unique=True)
    op.alter_column(
        "promocodes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("promocodes", "is_reusable")
    op.drop_column("promocodes", "is_trial")
    op.drop_column("promocodes", "plan_type")
    op.create_unique_constraint(
        op.f("uq_promocode_usage_per_student"),
        "promocode_usages",
        ["promocode_id", "student_guid"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "promocode_usages",
        "activated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("promocode_usages", "activated_plan")
    op.drop_column("payments", "subscription_plan")
    op.drop_column("payments", "is_subscription_payment")
    op.drop_index(
        "ix_subscription_history_subscription_id", table_name="subscription_history"
    )
    op.drop_index(
        "ix_subscription_history_created_at", table_name="subscription_history"
    )
    op.drop_table("subscription_history")
    op.drop_index("ix_subscriptions_user_status", table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index("ix_subscriptions_plan", table_name="subscriptions")
    op.drop_index("ix_subscriptions_expires_at", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(
        op.f("ix_subscription_plans_plan_type"), table_name="subscription_plans"
    )
    op.drop_index(
        op.f("ix_subscription_plans_is_active"), table_name="subscription_plans"
    )
    op.drop_index("ix_subscription_plans_active", table_name="subscription_plans")
    op.drop_table("subscription_plans")
    plantype_enum = postgresql.ENUM(
        "NONE", "FREE", "LITE", "PRO", "PREMIUM", name="plantype"
    )
    plantype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
