"""Init rating

Revision ID: 2c7d7adc4dd6
Revises: ef46d3424c53
Create Date: 2025-07-11 19:43:04.186650

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c7d7adc4dd6"
down_revision: Union[str, Sequence[str], None] = "f42a963c3c45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = sa.Enum("in_progress", "completed", "abandoned", name="status")


def upgrade() -> None:
    """Upgrade schema."""
    status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "last_rated_test_attempt_id",
        sa.Column("test_attempt_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("test_attempt_id"),
    )
    op.add_column("students", sa.Column("rating", sa.Integer(), nullable=False))
    op.add_column("test_attempts", sa.Column("status", status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_attempts", "status")
    op.drop_column("students", "rating")
    op.drop_table("last_rated_test_attempt_id")
    # ### end Alembic commands ###
