"""add student_guid to trainer_attempt_answers

Revision ID: 420aa383195e
Revises: fc858cd71edc
Create Date: 2025-10-09 10:47:08.000000

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "420aa383195e"
down_revision = "fc858cd71edc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trainer_attempt_answers",
        sa.Column("student_guid", postgresql.UUID(), nullable=True),
    )
    op.create_foreign_key(
        "fk_trainer_attempt_answers_student_guid",
        "trainer_attempt_answers",
        "students",
        ["student_guid"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_trainer_attempt_answers_student_guid",
        "trainer_attempt_answers",
        type_="foreignkey",
    )
    op.drop_column("trainer_attempt_answers", "student_guid")
    # ### end Alembic commands ###
