"""recreate lost migration a693b32eafaa

Revision ID: 4dd66c8a7769
Revises: 420aa383195e
Create Date: 2025-10-11 18:24:02.283664

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dd66c8a7769"
down_revision: Union[str, Sequence[str], None] = "420aa383195e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
