"""refactor relationships for cascade deleting

Revision ID: 59ee8afebfae
Revises: f926dff4350d
Create Date: 2025-10-18 10:19:13.026617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59ee8afebfae"
down_revision: Union[str, Sequence[str], None] = "f926dff4350d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("questions_hint_id_fkey"), "questions", type_="foreignkey")
    op.create_foreign_key(
        None, "questions", "hints", ["hint_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.create_foreign_key(
        op.f("questions_hint_id_fkey"),
        "questions",
        "hints",
        ["hint_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
