"""quiz major bugfix

Revision ID: 69ef19798589
Revises: 95342007a49b
Create Date: 2025-11-26 18:43:24.046807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69ef19798589"
down_revision: Union[str, Sequence[str], None] = "95342007a49b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_test_attempts", sa.Column("subject_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        "idx_daily_attempts_subject",
        "daily_test_attempts",
        ["subject_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "daily_test_attempts",
        "subjects",
        ["subject_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "ent_attempts", sa.Column("full_exam_question_ids", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ent_attempts", "full_exam_question_ids")
    op.drop_constraint(None, "daily_test_attempts", type_="foreignkey")
    op.drop_index("idx_daily_attempts_subject", table_name="daily_test_attempts")
    op.drop_column("daily_test_attempts", "subject_id")
    # ### end Alembic commands ###
