"""events_and_payments_dashboard_updates

Revision ID: 733be1126118
Revises: 4dd66c8a7769
Create Date: 2025-10-11 18:43:22.814487

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "733be1126118"
down_revision: Union[str, Sequence[str], None] = "4dd66c8a7769"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_activity",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("device_id", sa.String(length=255), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column(
            "event_time",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("platform", sa.String(length=50), nullable=True),
        sa.Column("app_version", sa.String(length=50), nullable=True),
        sa.Column("os_version", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_activity_device_id"), "user_activity", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_activity_event_name"),
        "user_activity",
        ["event_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activity_event_time"),
        "user_activity",
        ["event_time"],
        unique=False,
    )
    op.create_index(op.f("ix_user_activity_id"), "user_activity", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_activity_session_id"),
        "user_activity",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activity_user_id"), "user_activity", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_activity_user_id"), table_name="user_activity")
    op.drop_index(op.f("ix_user_activity_session_id"), table_name="user_activity")
    op.drop_index(op.f("ix_user_activity_id"), table_name="user_activity")
    op.drop_index(op.f("ix_user_activity_event_time"), table_name="user_activity")
    op.drop_index(op.f("ix_user_activity_event_name"), table_name="user_activity")
    op.drop_index(op.f("ix_user_activity_device_id"), table_name="user_activity")
    op.drop_table("user_activity")
    # ### end Alembic commands ###
