"""added progress func

Revision ID: 84749c3a9100
Revises: a41b14f47ff9
Create Date: 2025-12-05 17:32:14.036385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84749c3a9100"
down_revision: Union[str, Sequence[str], None] = "a41b14f47ff9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_question_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("attempt_type", sa.String(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column(
            "solved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_question",
        "user_question_progress",
        ["user_id", "question_id"],
        unique=True,
    )
    op.create_index(
        "idx_user_topic_progress",
        "user_question_progress",
        ["user_id", "question_id", "is_correct"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_question_progress_id"),
        "user_question_progress",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_question_progress_question_id"),
        "user_question_progress",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_question_progress_user_id"),
        "user_question_progress",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_question_progress_user_id"), table_name="user_question_progress"
    )
    op.drop_index(
        op.f("ix_user_question_progress_question_id"),
        table_name="user_question_progress",
    )
    op.drop_index(
        op.f("ix_user_question_progress_id"), table_name="user_question_progress"
    )
    op.drop_index("idx_user_topic_progress", table_name="user_question_progress")
    op.drop_index("idx_user_question", table_name="user_question_progress")
    op.drop_table("user_question_progress")
    # ### end Alembic commands ###
