"""remove unique test attempt question

Revision ID: 870998de3fbb
Revises: f6bf06f56356
Create Date: 2025-07-19 00:11:01.508460

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "870998de3fbb"
down_revision: Union[str, Sequence[str], None] = "f6bf06f56356"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uix_test_attempt_id_question_id"),
        "test_attempt_questions",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uix_test_attempt_id_question_id"),
        "test_attempt_questions",
        ["test_attempt_id", "question_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
