"""update question

Revision ID: 90b8e4de3431
Revises: 07fa99be186a
Create Date: 2025-09-14 19:27:15.820218

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90b8e4de3431"
down_revision: Union[str, Sequence[str], None] = "07fa99be186a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questions",
        "difficulty",
        existing_type=postgresql.ENUM("easy", "medium", "hard", name="difficulty"),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questions",
        "difficulty",
        existing_type=postgresql.ENUM("easy", "medium", "hard", name="difficulty"),
        nullable=False,
    )
    # ### end Alembic commands ###
