"""daily tests and full exam

Revision ID: 95342007a49b
Revises: 1e99634f4af5
Create Date: 2025-11-14 19:00:01.469452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95342007a49b'
down_revision: Union[str, Sequence[str], None] = '1e99634f4af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE examtype AS ENUM ('by_subject', 'full_exam')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_test_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('student_guid', sa.UUID(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('incorrect_answers', sa.Integer(), nullable=False),
    sa.Column('skipped_answers', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_guid'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_index('idx_daily_attempts_date', 'daily_test_attempts', ['test_date'], unique=False)
    op.create_index('idx_daily_attempts_student', 'daily_test_attempts', ['student_guid'], unique=False)
    op.create_table('daily_test_subject_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_guid', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_guid'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_guid', 'subject_id', name='uq_student_subject_preference')
    )
    op.create_index('idx_daily_subject_prefs_student', 'daily_test_subject_preferences', ['student_guid'], unique=False)
    op.create_table('daily_test_attempt_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_test_attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_test_attempt_id'], ['daily_test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_attempt_questions_attempt', 'daily_test_attempt_questions', ['daily_test_attempt_id'], unique=False)
    op.create_table('daily_test_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_test_attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_test_attempt_id'], ['daily_test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_answers_attempt', 'daily_test_answers', ['daily_test_attempt_id'], unique=False)
    op.add_column('ent_attempts', sa.Column('exam_type', sa.Enum('by_subject', 'full_exam', name='examtype'), server_default='by_subject', nullable=False))
    op.add_column('ent_attempts', sa.Column('subject_combination_id', sa.Integer(), nullable=True))
    op.add_column('ent_attempts', sa.Column('current_question_index', sa.Integer(), server_default='0', nullable=False))
    op.create_foreign_key('ent_attempts_subject_combination_fk', 'ent_attempts', 'ent_subject_combinations', ['subject_combination_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ent_attempts_subject_combination_fk', 'ent_attempts', type_='foreignkey')
    op.drop_column('ent_attempts', 'current_question_index')
    op.drop_column('ent_attempts', 'subject_combination_id')
    op.drop_column('ent_attempts', 'exam_type')
    op.drop_index('idx_daily_answers_attempt', table_name='daily_test_answers')
    op.drop_table('daily_test_answers')
    op.drop_index('idx_daily_attempt_questions_attempt', table_name='daily_test_attempt_questions')
    op.drop_table('daily_test_attempt_questions')
    op.drop_index('idx_daily_subject_prefs_student', table_name='daily_test_subject_preferences')
    op.drop_table('daily_test_subject_preferences')
    op.drop_index('idx_daily_attempts_student', table_name='daily_test_attempts')
    op.drop_index('idx_daily_attempts_date', table_name='daily_test_attempts')
    op.drop_table('daily_test_attempts')

    op.execute("DROP TYPE examtype")
    # ### end Alembic commands ###
