"""cashback system

Revision ID: 9c8edd56088b
Revises: a43fc4cdc2f0
Create Date: 2026-02-17 22:50:25.338998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c8edd56088b"
down_revision: Union[str, Sequence[str], None] = "a43fc4cdc2f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cashback_daily_completions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_guid", sa.UUID(), nullable=False),
        sa.Column("completion_date", sa.Date(), nullable=False),
        sa.Column("streak_number", sa.Integer(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("reward_earned", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["student_guid"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_guid", "completion_date", name="uq_cashback_daily_student_date"
        ),
    )
    op.create_index(
        op.f("ix_cashback_daily_completions_student_guid"),
        "cashback_daily_completions",
        ["student_guid"],
        unique=False,
    )
    op.create_index(
        "ix_cashback_daily_student_date",
        "cashback_daily_completions",
        ["student_guid", "completion_date"],
        unique=False,
    )
    op.create_table(
        "cashback_reward_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_guid", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "awarded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("streak_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["student_guid"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cashback_reward_history_student_guid"),
        "cashback_reward_history",
        ["student_guid"],
        unique=False,
    )
    op.create_table(
        "cashback_user_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_guid", sa.UUID(), nullable=False),
        sa.Column("current_streak_number", sa.Integer(), nullable=False),
        sa.Column("current_day_in_streak", sa.Integer(), nullable=False),
        sa.Column("total_streaks_completed", sa.Integer(), nullable=False),
        sa.Column("total_cashback_earned", sa.Integer(), nullable=False),
        sa.Column("last_completed_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["student_guid"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cashback_user_states_student_guid"),
        "cashback_user_states",
        ["student_guid"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cashback_user_states_student_guid"), table_name="cashback_user_states"
    )
    op.drop_table("cashback_user_states")
    op.drop_index(
        op.f("ix_cashback_reward_history_student_guid"),
        table_name="cashback_reward_history",
    )
    op.drop_table("cashback_reward_history")
    op.drop_index(
        "ix_cashback_daily_student_date", table_name="cashback_daily_completions"
    )
    op.drop_index(
        op.f("ix_cashback_daily_completions_student_guid"),
        table_name="cashback_daily_completions",
    )
    op.drop_table("cashback_daily_completions")
    # ### end Alembic commands ###
