"""module system

Revision ID: a43fc4cdc2f0
Revises: ef87741a964d
Create Date: 2026-02-08 09:01:54.004937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "a43fc4cdc2f0"
down_revision: Union[str, Sequence[str], None] = "ef87741a964d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Используем существующие ENUM типы, а не создаем новые
    difficulty_enum = postgresql.ENUM(
        "easy", "medium", "hard", name="difficulty", create_type=False
    )
    status_enum = postgresql.ENUM(
        "in_progress", "completed", name="status", create_type=False
    )

    op.create_table(
        "subject_modules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )
    op.create_index("idx_module_active", "subject_modules", ["is_active"], unique=False)
    op.create_index(
        "idx_module_subject_order",
        "subject_modules",
        ["subject_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "module_lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("video_url", sa.String(length=500), nullable=True),
        sa.Column("presentation_url", sa.String(length=500), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("difficulty", difficulty_enum, nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["module_id"], ["subject_modules.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )
    op.create_index(
        "idx_lesson_module_order",
        "module_lessons",
        ["module_id", "order_index"],
        unique=False,
    )
    op.create_index(
        "idx_lesson_published", "module_lessons", ["is_published"], unique=False
    )
    op.create_index("idx_lesson_topic", "module_lessons", ["topic_id"], unique=False)
    op.create_index(
        op.f("ix_module_lessons_topic_id"), "module_lessons", ["topic_id"], unique=False
    )
    op.create_table(
        "module_tests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pass_score_percentage", sa.Integer(), nullable=False),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["module_id"], ["subject_modules.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
        sa.UniqueConstraint("module_id"),
    )
    op.create_index(
        "idx_module_test_active", "module_tests", ["is_active"], unique=False
    )
    op.create_table(
        "user_module_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_guid", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("completed_lessons_count", sa.Integer(), nullable=False),
        sa.Column("total_lessons_count", sa.Integer(), nullable=False),
        sa.Column("module_test_completed", sa.Boolean(), nullable=False),
        sa.Column("module_test_score", sa.Integer(), nullable=False),
        sa.Column("module_test_max_score", sa.Integer(), nullable=False),
        sa.Column("module_test_percentage", sa.Float(), nullable=False),
        sa.Column("module_test_attempts_count", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("overall_progress_percentage", sa.Float(), nullable=False),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["module_id"], ["subject_modules.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_guid", "module_id", name="uq_user_module"),
    )
    op.create_index(
        "idx_module_progress",
        "user_module_progress",
        ["module_id", "is_completed"],
        unique=False,
    )
    op.create_index(
        "idx_user_module_completed",
        "user_module_progress",
        ["student_guid", "is_completed"],
        unique=False,
    )
    op.create_index(
        "idx_user_module_progress",
        "user_module_progress",
        ["student_guid", "module_id"],
        unique=False,
    )
    op.create_table(
        "lesson_tests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pass_score_percentage", sa.Integer(), nullable=False),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"], ["module_lessons.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
        sa.UniqueConstraint("lesson_id"),
    )
    op.create_index(
        "idx_lesson_test_active", "lesson_tests", ["is_active"], unique=False
    )
    op.create_table(
        "module_test_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.UUID(), nullable=False),
        sa.Column("module_test_id", sa.Integer(), nullable=False),
        sa.Column("student_guid", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", status_enum, nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=False),
        sa.Column("is_passed", sa.Boolean(), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["module_test_id"], ["module_tests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )
    op.create_index(
        "idx_module_test_attempt_status",
        "module_test_attempts",
        ["status"],
        unique=False,
    )
    op.create_index(
        "idx_module_test_attempt_student",
        "module_test_attempts",
        ["student_guid", "module_test_id"],
        unique=False,
    )
    op.create_table(
        "module_test_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("module_test_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["module_test_id"], ["module_tests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "module_test_id", "question_id", name="uq_module_test_question"
        ),
    )
    op.create_index(
        "idx_module_test_question_order",
        "module_test_questions",
        ["module_test_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "user_lesson_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_guid", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("watched_video", sa.Boolean(), nullable=False),
        sa.Column("viewed_presentation", sa.Boolean(), nullable=False),
        sa.Column("read_content", sa.Boolean(), nullable=False),
        sa.Column("completed_test", sa.Boolean(), nullable=False),
        sa.Column("test_score", sa.Integer(), nullable=False),
        sa.Column("test_max_score", sa.Integer(), nullable=False),
        sa.Column("test_percentage", sa.Float(), nullable=False),
        sa.Column("test_attempts_count", sa.Integer(), nullable=False),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "last_accessed_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"], ["module_lessons.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_guid", "lesson_id", name="uq_user_lesson"),
    )
    op.create_index(
        "idx_lesson_progress",
        "user_lesson_progress",
        ["lesson_id", "is_completed"],
        unique=False,
    )
    op.create_index(
        "idx_user_lesson_completed",
        "user_lesson_progress",
        ["student_guid", "is_completed"],
        unique=False,
    )
    op.create_index(
        "idx_user_lesson_progress",
        "user_lesson_progress",
        ["student_guid", "lesson_id"],
        unique=False,
    )
    op.create_table(
        "lesson_test_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.UUID(), nullable=False),
        sa.Column("lesson_test_id", sa.Integer(), nullable=False),
        sa.Column("student_guid", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", status_enum, nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=False),
        sa.Column("is_passed", sa.Boolean(), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lesson_test_id"], ["lesson_tests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )
    op.create_index(
        "idx_lesson_test_attempt_status",
        "lesson_test_attempts",
        ["status"],
        unique=False,
    )
    op.create_index(
        "idx_lesson_test_attempt_student",
        "lesson_test_attempts",
        ["student_guid", "lesson_test_id"],
        unique=False,
    )
    op.create_table(
        "lesson_test_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_test_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lesson_test_id"], ["lesson_tests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "lesson_test_id", "question_id", name="uq_lesson_test_question"
        ),
    )
    op.create_index(
        "idx_lesson_test_question_order",
        "lesson_test_questions",
        ["lesson_test_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "module_test_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("module_test_attempt_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("points_earned", sa.Integer(), nullable=False),
        sa.Column(
            "answered_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["module_test_attempt_id"], ["module_test_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["variants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_module_test_answer_attempt",
        "module_test_answers",
        ["module_test_attempt_id"],
        unique=False,
    )
    op.create_index(
        "idx_module_test_answer_question",
        "module_test_answers",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "lesson_test_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_test_attempt_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("points_earned", sa.Integer(), nullable=False),
        sa.Column(
            "answered_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lesson_test_attempt_id"], ["lesson_test_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["variants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_lesson_test_answer_attempt",
        "lesson_test_answers",
        ["lesson_test_attempt_id"],
        unique=False,
    )
    op.create_index(
        "idx_lesson_test_answer_question",
        "lesson_test_answers",
        ["question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_lesson_test_answer_question", table_name="lesson_test_answers")
    op.drop_index("idx_lesson_test_answer_attempt", table_name="lesson_test_answers")
    op.drop_table("lesson_test_answers")
    op.drop_index("idx_module_test_answer_question", table_name="module_test_answers")
    op.drop_index("idx_module_test_answer_attempt", table_name="module_test_answers")
    op.drop_table("module_test_answers")
    op.drop_index("idx_lesson_test_question_order", table_name="lesson_test_questions")
    op.drop_table("lesson_test_questions")
    op.drop_index("idx_lesson_test_attempt_student", table_name="lesson_test_attempts")
    op.drop_index("idx_lesson_test_attempt_status", table_name="lesson_test_attempts")
    op.drop_table("lesson_test_attempts")
    op.drop_index("idx_user_lesson_progress", table_name="user_lesson_progress")
    op.drop_index("idx_user_lesson_completed", table_name="user_lesson_progress")
    op.drop_index("idx_lesson_progress", table_name="user_lesson_progress")
    op.drop_table("user_lesson_progress")
    op.drop_index("idx_module_test_question_order", table_name="module_test_questions")
    op.drop_table("module_test_questions")
    op.drop_index("idx_module_test_attempt_student", table_name="module_test_attempts")
    op.drop_index("idx_module_test_attempt_status", table_name="module_test_attempts")
    op.drop_table("module_test_attempts")
    op.drop_index("idx_lesson_test_active", table_name="lesson_tests")
    op.drop_table("lesson_tests")
    op.drop_index("idx_user_module_progress", table_name="user_module_progress")
    op.drop_index("idx_user_module_completed", table_name="user_module_progress")
    op.drop_index("idx_module_progress", table_name="user_module_progress")
    op.drop_table("user_module_progress")
    op.drop_index("idx_module_test_active", table_name="module_tests")
    op.drop_table("module_tests")
    op.drop_index(op.f("ix_module_lessons_topic_id"), table_name="module_lessons")
    op.drop_index("idx_lesson_topic", table_name="module_lessons")
    op.drop_index("idx_lesson_published", table_name="module_lessons")
    op.drop_index("idx_lesson_module_order", table_name="module_lessons")
    op.drop_table("module_lessons")
    op.drop_index("idx_module_subject_order", table_name="subject_modules")
    op.drop_index("idx_module_active", table_name="subject_modules")
    op.drop_table("subject_modules")
    # ### end Alembic commands ###
