"""bank

Revision ID: bdab54e499a9
Revises: 9c8edd56088b
Create Date: 2026-03-05 16:26:56.864156

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bdab54e499a9"
down_revision: Union[str, Sequence[str], None] = "9c8edd56088b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_styles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )
    op.create_table(
        "user_bank_accounts",
        sa.Column("guid", sa.UUID(), nullable=False),
        sa.Column("student_guid", sa.UUID(), nullable=False),
        sa.Column("card_style_id", sa.Integer(), nullable=False),
        sa.Column("card_number", sa.String(length=16), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["card_style_id"],
            ["card_styles.id"],
        ),
        sa.PrimaryKeyConstraint("guid"),
        sa.UniqueConstraint("card_number"),
    )
    op.create_index(
        "ix_bank_account_student", "user_bank_accounts", ["student_guid"], unique=False
    )
    op.create_index(
        op.f("ix_user_bank_accounts_student_guid"),
        "user_bank_accounts",
        ["student_guid"],
        unique=True,
    )
    op.create_table(
        "transactions",
        sa.Column("guid", sa.UUID(), nullable=False),
        sa.Column("account_guid", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("deposit", "withdrawal", name="transactiontype"),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "completed", "failed", "cancelled", name="transactionstatus"
            ),
            nullable=False,
        ),
        sa.Column("additional_metadata", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["account_guid"], ["user_bank_accounts.guid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("guid"),
    )
    op.create_index(
        "ix_transactions_account", "transactions", ["account_guid"], unique=False
    )
    op.create_index(
        "ix_transactions_created", "transactions", ["created_at"], unique=False
    )
    op.create_table(
        "withdrawal_requests",
        sa.Column("guid", sa.UUID(), nullable=False),
        sa.Column("account_guid", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("iban", sa.String(length=50), nullable=False),
        sa.Column("card_number", sa.String(length=16), nullable=False),
        sa.Column("card_holder", sa.String(length=200), nullable=False),
        sa.Column("iin", sa.String(length=12), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "cancelled",
                name="withdrawalrequeststatus",
            ),
            nullable=False,
        ),
        sa.Column("admin_comment", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["account_guid"], ["user_bank_accounts.guid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("guid"),
    )
    op.create_index(
        "ix_withdrawal_requests_account",
        "withdrawal_requests",
        ["account_guid"],
        unique=False,
    )
    op.create_index(
        "ix_withdrawal_requests_created",
        "withdrawal_requests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_withdrawal_requests_status", "withdrawal_requests", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_withdrawal_requests_status", table_name="withdrawal_requests")
    op.drop_index("ix_withdrawal_requests_created", table_name="withdrawal_requests")
    op.drop_index("ix_withdrawal_requests_account", table_name="withdrawal_requests")
    op.drop_table("withdrawal_requests")
    op.drop_index("ix_transactions_created", table_name="transactions")
    op.drop_index("ix_transactions_account", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(
        op.f("ix_user_bank_accounts_student_guid"), table_name="user_bank_accounts"
    )
    op.drop_index("ix_bank_account_student", table_name="user_bank_accounts")
    op.drop_table("user_bank_accounts")
    op.drop_table("card_styles")
    # ### end Alembic commands ###
