"""statistics update

Revision ID: c199ba36cb59
Revises: c0267b44bad2
Create Date: 2025-12-11 15:32:05.639637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c199ba36cb59"
down_revision: Union[str, Sequence[str], None] = "c0267b44bad2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ent_attempts",
        sa.Column("original_completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "ent_attempts",
        sa.Column("time_correction_applied", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "ent_attempts", sa.Column("correction_reason", sa.String(), nullable=True)
    )
    op.drop_constraint(
        op.f("promocode_usages_student_guid_fkey"),
        "promocode_usages",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("promocode_usages_promocode_id_fkey"),
        "promocode_usages",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "promocode_usages", "promocodes", ["promocode_id"], ["id"]
    )
    op.alter_column("promocodes", "created_by", existing_type=sa.UUID(), nullable=False)
    op.add_column(
        "trainer_attempts",
        sa.Column("active_time_seconds", sa.Integer(), nullable=True),
    )
    op.add_column(
        "trainer_attempts",
        sa.Column("time_correction_applied", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trainer_attempts", "time_correction_applied")
    op.drop_column("trainer_attempts", "active_time_seconds")
    op.alter_column("promocodes", "created_by", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(None, "promocode_usages", type_="foreignkey")
    op.create_foreign_key(
        op.f("promocode_usages_promocode_id_fkey"),
        "promocode_usages",
        "promocodes",
        ["promocode_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("promocode_usages_student_guid_fkey"),
        "promocode_usages",
        "students",
        ["student_guid"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("ent_attempts", "correction_reason")
    op.drop_column("ent_attempts", "time_correction_applied")
    op.drop_column("ent_attempts", "original_completed_at")
    # ### end Alembic commands ###
