"""image_url -> image_path

Revision ID: e0ff4d7f0a5a
Revises: 870998de3fbb
Create Date: 2025-08-13 01:04:56.697817

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0ff4d7f0a5a"
down_revision: Union[str, Sequence[str], None] = "870998de3fbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hints", sa.Column("image_path", sa.String(), nullable=True))
    op.drop_column("hints", "image_url")
    op.add_column("questions", sa.Column("image_path", sa.String(), nullable=True))
    op.drop_column("questions", "image_url")
    op.add_column("variants", sa.Column("image_path", sa.String(), nullable=True))
    op.drop_column("variants", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "variants",
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("variants", "image_path")
    op.add_column(
        "questions",
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("questions", "image_path")
    op.add_column(
        "hints",
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("hints", "image_path")
    # ### end Alembic commands ###
