"""updated numeration of ent options

Revision ID: ef87741a964d
Revises: c199ba36cb59
Create Date: 2026-02-02 14:42:23.065057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef87741a964d"
down_revision: Union[str, Sequence[str], None] = "c199ba36cb59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance_streaks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_guid", sa.UUID(), nullable=False),
        sa.Column("current_streak_days", sa.Integer(), nullable=True),
        sa.Column("longest_streak_days", sa.Integer(), nullable=True),
        sa.Column("total_points", sa.Integer(), nullable=True),
        sa.Column("current_cycle_days", sa.Integer(), nullable=True),
        sa.Column("completed_cycles_count", sa.Integer(), nullable=True),
        sa.Column("last_activity_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_streaks_student_guid"),
        "attendance_streaks",
        ["student_guid"],
        unique=False,
    )
    op.create_table(
        "attendance_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attendance_streak_id", sa.Integer(), nullable=False),
        sa.Column("activity_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=True),
        sa.Column("streak_days_at_activity", sa.Integer(), nullable=True),
        sa.Column("multiplier_at_activity", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["attendance_streak_id"],
            ["attendance_streaks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_attendance_log_streak_date",
        "attendance_logs",
        ["attendance_streak_id", "activity_date"],
        unique=False,
    )
    op.drop_constraint(
        op.f("ent_options_option_number_key"), "ent_options", type_="unique"
    )
    op.create_unique_constraint(
        "ent_options_subject_option_unique",
        "ent_options",
        ["subject_id", "option_number"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ent_options_subject_option_unique", "ent_options", type_="unique"
    )
    op.create_unique_constraint(
        op.f("ent_options_option_number_key"),
        "ent_options",
        ["option_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index("ix_attendance_log_streak_date", table_name="attendance_logs")
    op.drop_table("attendance_logs")
    op.drop_index(
        op.f("ix_attendance_streaks_student_guid"), table_name="attendance_streaks"
    )
    op.drop_table("attendance_streaks")
    # ### end Alembic commands ###
