"""return hint

Revision ID: f6bf06f56356
Revises: 2c7d7adc4dd6
Create Date: 2025-07-14 23:28:37.178411

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6bf06f56356"
down_revision: Union[str, Sequence[str], None] = "2c7d7adc4dd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("hints_question_id_key"), "hints", type_="unique")
    op.drop_constraint(op.f("hints_question_id_fkey"), "hints", type_="foreignkey")
    op.drop_column("hints", "question_id")
    op.add_column("questions", sa.Column("hint_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "questions", "hints", ["hint_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.drop_column("questions", "hint_id")
    op.add_column(
        "hints",
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("hints_question_id_fkey"),
        "hints",
        "questions",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("hints_question_id_key"),
        "hints",
        ["question_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
