"""added cascade' drop values

Revision ID: f926dff4350d
Revises: fa2f4665db0b
Create Date: 2025-10-18 09:52:21.380313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f926dff4350d"
down_revision: Union[str, Sequence[str], None] = "fa2f4665db0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ent_attempt_answers_variant_id_fkey"),
        "ent_attempt_answers",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("ent_attempt_answers_ent_attempt_id_fkey"),
        "ent_attempt_answers",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "ent_attempt_answers",
        "variants",
        ["variant_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "ent_attempt_answers",
        "ent_attempts",
        ["ent_attempt_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("ent_options_subject_id_fkey"), "ent_options", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "ent_options", "subjects", ["subject_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("ent_questions_ent_option_id_fkey"), "ent_questions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("ent_questions_question_id_fkey"), "ent_questions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "ent_questions", "questions", ["question_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "ent_questions",
        "ent_options",
        ["ent_option_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("ent_subject_combinations_specialized_subject_1_id_fkey"),
        "ent_subject_combinations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("ent_subject_combinations_specialized_subject_2_id_fkey"),
        "ent_subject_combinations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "ent_subject_combinations",
        "subjects",
        ["specialized_subject_2_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "ent_subject_combinations",
        "subjects",
        ["specialized_subject_1_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("questions_hint_id_fkey"), "questions", type_="foreignkey")
    op.drop_constraint(op.f("questions_topic_id_fkey"), "questions", type_="foreignkey")
    op.drop_constraint(
        op.f("questions_subject_id_fkey"), "questions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "questions", "subjects", ["subject_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "questions", "topics", ["topic_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "questions", "hints", ["hint_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(op.f("topics_subject_id_fkey"), "topics", type_="foreignkey")
    op.create_foreign_key(
        None, "topics", "subjects", ["subject_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("trainer_attempt_answers_trainer_attempt_question_id_fkey"),
        "trainer_attempt_answers",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "trainer_attempt_answers",
        "trainer_attempt_questions",
        ["trainer_attempt_question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("trainer_attempt_questions_trainer_attempt_id_fkey"),
        "trainer_attempt_questions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "trainer_attempt_questions",
        "trainer_attempts",
        ["trainer_attempt_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("trainer_attempts_trainer_id_fkey"), "trainer_attempts", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "trainer_attempts", "trainers", ["trainer_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("trainer_questions_question_id_fkey"),
        "trainer_questions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("trainer_questions_trainer_id_fkey"),
        "trainer_questions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "trainer_questions",
        "trainers",
        ["trainer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "trainer_questions",
        "questions",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("trainers_topic_id_fkey"), "trainers", type_="foreignkey")
    op.create_foreign_key(
        None, "trainers", "topics", ["topic_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trainers", type_="foreignkey")
    op.create_foreign_key(
        op.f("trainers_topic_id_fkey"), "trainers", "topics", ["topic_id"], ["id"]
    )
    op.drop_constraint(None, "trainer_questions", type_="foreignkey")
    op.drop_constraint(None, "trainer_questions", type_="foreignkey")
    op.create_foreign_key(
        op.f("trainer_questions_trainer_id_fkey"),
        "trainer_questions",
        "trainers",
        ["trainer_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("trainer_questions_question_id_fkey"),
        "trainer_questions",
        "questions",
        ["question_id"],
        ["id"],
    )
    op.drop_constraint(None, "trainer_attempts", type_="foreignkey")
    op.create_foreign_key(
        op.f("trainer_attempts_trainer_id_fkey"),
        "trainer_attempts",
        "trainers",
        ["trainer_id"],
        ["id"],
    )
    op.drop_constraint(None, "trainer_attempt_questions", type_="foreignkey")
    op.create_foreign_key(
        op.f("trainer_attempt_questions_trainer_attempt_id_fkey"),
        "trainer_attempt_questions",
        "trainer_attempts",
        ["trainer_attempt_id"],
        ["id"],
    )
    op.drop_constraint(None, "trainer_attempt_answers", type_="foreignkey")
    op.create_foreign_key(
        op.f("trainer_attempt_answers_trainer_attempt_question_id_fkey"),
        "trainer_attempt_answers",
        "trainer_attempt_questions",
        ["trainer_attempt_question_id"],
        ["id"],
    )
    op.drop_constraint(None, "topics", type_="foreignkey")
    op.create_foreign_key(
        op.f("topics_subject_id_fkey"), "topics", "subjects", ["subject_id"], ["id"]
    )
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.create_foreign_key(
        op.f("questions_subject_id_fkey"),
        "questions",
        "subjects",
        ["subject_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("questions_topic_id_fkey"), "questions", "topics", ["topic_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("questions_hint_id_fkey"), "questions", "hints", ["hint_id"], ["id"]
    )
    op.drop_constraint(None, "ent_subject_combinations", type_="foreignkey")
    op.drop_constraint(None, "ent_subject_combinations", type_="foreignkey")
    op.create_foreign_key(
        op.f("ent_subject_combinations_specialized_subject_2_id_fkey"),
        "ent_subject_combinations",
        "subjects",
        ["specialized_subject_2_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("ent_subject_combinations_specialized_subject_1_id_fkey"),
        "ent_subject_combinations",
        "subjects",
        ["specialized_subject_1_id"],
        ["id"],
    )
    op.drop_constraint(None, "ent_questions", type_="foreignkey")
    op.drop_constraint(None, "ent_questions", type_="foreignkey")
    op.create_foreign_key(
        op.f("ent_questions_question_id_fkey"),
        "ent_questions",
        "questions",
        ["question_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("ent_questions_ent_option_id_fkey"),
        "ent_questions",
        "ent_options",
        ["ent_option_id"],
        ["id"],
    )
    op.drop_constraint(None, "ent_options", type_="foreignkey")
    op.create_foreign_key(
        op.f("ent_options_subject_id_fkey"),
        "ent_options",
        "subjects",
        ["subject_id"],
        ["id"],
    )
    op.drop_constraint(None, "ent_attempt_answers", type_="foreignkey")
    op.drop_constraint(None, "ent_attempt_answers", type_="foreignkey")
    op.create_foreign_key(
        op.f("ent_attempt_answers_ent_attempt_id_fkey"),
        "ent_attempt_answers",
        "ent_attempts",
        ["ent_attempt_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("ent_attempt_answers_variant_id_fkey"),
        "ent_attempt_answers",
        "variants",
        ["variant_id"],
        ["id"],
    )
    # ### end Alembic commands ###
