"""added index to ent_attempts

Revision ID: fa2f4665db0b
Revises: 733be1126118
Create Date: 2025-10-15 22:15:05.424238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa2f4665db0b"
down_revision: Union[str, Sequence[str], None] = "733be1126118"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_unique_active_ent_attempt",
        "ent_attempts",
        ["student_guid", "ent_option_id"],
        unique=True,
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_unique_active_ent_attempt",
        table_name="ent_attempts",
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    # ### end Alembic commands ###
