"""migration fix

Revision ID: fc858cd71edc
Revises: 8502e2303f3d
Create Date: 2025-10-05 08:13:12.423080

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc858cd71edc"
down_revision: Union[str, Sequence[str], None] = "8502e2303f3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

test_status = postgresql.ENUM(
    "in_progress", "completed", "abandoned", name="status", create_type=False
)
question_type = sa.Enum(
    "single_choice", "multiple_choice", "matching", name="questiontype"
)
subject_type = sa.Enum("main", "specialized", name="subjecttype")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    question_type.create(op.get_bind(), checkfirst=True)
    subject_type.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "ent_options",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guid", sa.UUID(), nullable=True),
        sa.Column("option_number", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
        sa.UniqueConstraint("option_number"),
    )
    op.create_table(
        "ent_subject_combinations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("specialized_subject_1_id", sa.Integer(), nullable=False),
        sa.Column("specialized_subject_2_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["specialized_subject_1_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specialized_subject_2_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ent_attempts",
        sa.Column("guid", sa.UUID(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ent_option_id", sa.Integer(), nullable=True),
        sa.Column("student_guid", sa.UUID(), nullable=False),
        sa.Column("status", test_status, nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column(
            "started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deadline_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ent_option_id"], ["ent_options.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )
    op.create_table(
        "trainers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )
    op.create_table(
        "ent_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.UUID(), nullable=True),
        sa.Column("ent_option_id", sa.Integer(), nullable=True),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ent_option_id"],
            ["ent_options.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )
    op.create_table(
        "trainer_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trainer_id", sa.Integer(), nullable=False),
        sa.Column("student_guid", sa.UUID(), nullable=False),
        sa.Column("status", test_status, nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trainer_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trainer_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ent_attempt_answers",
        sa.Column("guid", sa.UUID(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ent_attempt_id", sa.Integer(), nullable=True),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ent_attempt_id"],
            ["ent_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )
    op.create_table(
        "text_block_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("hint_id", sa.Integer(), nullable=True),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["hint_id"], ["hints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["variants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hint_id"),
        sa.UniqueConstraint("question_id"),
        sa.UniqueConstraint("variant_id"),
    )
    op.create_table(
        "trainer_attempt_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trainer_attempt_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("spend_time", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["trainer_attempt_id"],
            ["trainer_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "question_blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("text", "media", name="blocktype"), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("text_block_link_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["text_block_link_id"], ["text_block_links.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trainer_attempt_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trainer_attempt_question_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["trainer_attempt_question_id"],
            ["trainer_attempt_questions.id"],
        ),
        sa.ForeignKeyConstraint(["variant_id"], ["variants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.drop_table('ent_attempt_answer')
    # op.drop_table('ent_attempt')
    # op.drop_table('test_attempt_answers')
    # op.drop_table('test_attempt_questions')
    # op.drop_table('test_attempts')
    op.add_column('hints', sa.Column('guid', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, "hints", ["guid"])
    # op.drop_column('hints', 'image_path')
    # op.drop_column('hints', 'data')
    op.add_column('questions', sa.Column('guid', sa.UUID(), nullable=True))
    op.add_column('questions', sa.Column('question_type', question_type, nullable=True))
    op.create_unique_constraint(None, "questions", ["guid"])
    # op.drop_constraint(op.f('questions_ent_option_id_fkey'), 'questions', type_='foreignkey')
    # op.drop_column('questions', 'ent_option_id')
    # op.drop_column('questions', 'image_path')
    # op.drop_column('questions', 'data')
    # op.drop_column('questions', 'type')
    op.add_column('subjects', sa.Column('guid', sa.UUID(), nullable=True))
    op.add_column('subjects', sa.Column('type', subject_type, nullable=True))
    op.create_unique_constraint(None, "subjects", ["guid"])
    op.add_column('topics', sa.Column('guid', sa.UUID(), nullable=True))
    op.add_column('topics', sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=True))
    op.create_unique_constraint(None, "topics", ["guid"])
    op.add_column('variants', sa.Column('guid', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, "variants", ["guid"])
    # op.drop_column('variants', 'image_path')
    # op.drop_column('variants', 'data')
    # op.drop_table('ent_option')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "variants", sa.Column("data", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "variants",
        sa.Column("image_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "variants", type_="unique")
    op.drop_column("variants", "guid")
    op.drop_constraint(None, "topics", type_="unique")
    op.drop_column("topics", "difficulty")
    op.drop_column("topics", "guid")
    op.drop_constraint(None, "subjects", type_="unique")
    op.drop_column("subjects", "type")
    op.drop_column("subjects", "guid")
    op.add_column(
        "questions",
        sa.Column(
            "type",
            postgresql.ENUM("unrated", "rated", "ent", name="testtype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "questions", sa.Column("data", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "questions",
        sa.Column("image_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("ent_option_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("questions_ent_option_id_fkey"),
        "questions",
        "ent_option",
        ["ent_option_id"],
        ["id"],
    )
    op.drop_constraint(None, "questions", type_="unique")
    op.drop_column("questions", "question_type")
    op.drop_column("questions", "guid")
    op.add_column(
        "hints", sa.Column("data", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "hints",
        sa.Column("image_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "hints", type_="unique")
    op.drop_column("hints", "guid")
    op.create_table(
        "test_attempts",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('test_attempts_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("topic_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("student_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("unrated", "rated", "ent", name="testtype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deadline_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "status",
            postgresql.ENUM("in_progress", "completed", "abandoned", name="status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name="test_attempts_topic_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="test_attempts_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "ent_attempt_answer",
        sa.Column("guid", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("ent_attempt_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("variant_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["ent_attempt_id"],
            ["ent_attempt.id"],
            name=op.f("ent_attempt_answer_ent_attempt_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("ent_attempt_answer_question_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
            name=op.f("ent_attempt_answer_variant_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ent_attempt_answer_pkey")),
        sa.UniqueConstraint(
            "guid",
            name=op.f("ent_attempt_answer_guid_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "test_attempt_questions",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('test_attempt_questions_id_seq'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("test_attempt_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "spend_time",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name="test_attempt_questions_question_id_fkey",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["test_attempt_id"],
            ["test_attempts.id"],
            name="test_attempt_questions_test_attempt_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="test_attempt_questions_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "test_attempt_answers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "test_attempt_question_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("variant_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_correct", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["test_attempt_question_id"],
            ["test_attempt_questions.id"],
            name=op.f("test_attempt_answers_test_attempt_question_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
            name=op.f("test_attempt_answers_variant_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("test_attempt_answers_pkey")),
    )
    op.create_table(
        "ent_attempt",
        sa.Column("guid", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("ent_option_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("student_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("in_progress", "completed", "abandoned", name="status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deadline_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["ent_option_id"],
            ["ent_option.id"],
            name=op.f("ent_attempt_ent_option_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ent_attempt_pkey")),
        sa.UniqueConstraint(
            "guid",
            name=op.f("ent_attempt_guid_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "ent_option",
        sa.Column("guid", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("option_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("ent_option_pkey")),
        sa.UniqueConstraint(
            "guid",
            name=op.f("ent_option_guid_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "option_number",
            name=op.f("ent_option_option_number_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("trainer_attempt_answers")
    op.drop_table("question_blocks")
    op.drop_table("trainer_attempt_questions")
    op.drop_table("text_block_links")
    op.drop_table("ent_attempt_answers")
    op.drop_table("trainer_questions")
    op.drop_table("trainer_attempts")
    op.drop_table("ent_questions")
    op.drop_table("trainers")
    op.drop_table("ent_attempts")
    op.drop_table("ent_subject_combinations")
    op.drop_table("ent_options")
    question_type.drop(op.get_bind(), checkfirst=True)
    subject_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
